select * from hotel_data;

--Total bookings in City and Resort hotels
SELECT
	'City Hotel' AS hotel_type,
	COUNT(hotel) AS total_bookings
FROM hotel_data
WHERE hotel = 'City Hotel'
UNION
SELECT
	'Resort Hotel',
	COUNT(hotel)
FROM hotel_data
WHERE hotel = 'Resort Hotel';

-- Percentage of City and Resort hotel bookings

SELECT
	'City Hotel' AS hotel_type,
	ROUND(COUNT(hotel) * 100.0
		/ (SELECT COUNT(hotel)
		FROM hotel_data),2) AS percent_of_bookings
FROM hotel_data
WHERE hotel = 'City Hotel'
UNION
SELECT
	'Resort Hotel',
	ROUND(COUNT(hotel) * 100.0
		/ (SELECT COUNT(hotel)
		FROM hotel_data),2)
FROM hotel_data
WHERE hotel = 'Resort Hotel';


--Let's calculate Revenue  

Select sum(stays_in_week_nights+stays_in_weekend_nights)
FROM hotel_data;

--Revenue generated by year in both hotels
SELECT arrival_date_year, 
 sum((stays_in_week_nights+stays_in_weekend_nights) * adr) AS revenue
FROM hotel_data
GROUP BY arrival_date_year


--Total Bookings
select hotel, count(is_canceled) as booked from hotel_data where is_canceled = 0
group by hotel;

---Total cancellations
select hotel, count(is_canceled) as booked from hotel_data where is_canceled = 1
group by hotel;

---Country with most repeated guests in both hotels
select country, count(is_repeated_guest) as total_count_resort from hotel_data 
group by country
order by total_count_resort DESC
limit 10;


---Total bookings in both hotels by month.

SELECT arrival_date_month,
	CASE
		WHEN arrival_date_month = 'January' THEN 1
		WHEN arrival_date_month = 'February' THEN 2
		WHEN arrival_date_month = 'March' THEN 3
		WHEN arrival_date_month = 'April' THEN 4
		WHEN arrival_date_month = 'May' THEN 5
		WHEN arrival_date_month = 'June' THEN 6
		WHEN arrival_date_month = 'July' THEN 7
		WHEN arrival_date_month = 'August' THEN 8
		WHEN arrival_date_month = 'September' THEN 9
		WHEN arrival_date_month = 'October' THEN 10
		WHEN arrival_date_month = 'November' THEN 11
		WHEN arrival_date_month = 'December' THEN 12
	END AS months,
	COUNT(hotel) AS total_bookings
FROM hotel_data
GROUP BY arrival_date_month
ORDER BY months;


